// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaMGJwGBConRQKednkOT89IUnGDLlHxs4',
    appId: '1:962549560222:web:0f6cba02ca34e87f0e5c8f',
    messagingSenderId: '962549560222',
    projectId: 'acudrop-71231',
    authDomain: 'acudrop-71231.firebaseapp.com',
    storageBucket: 'acudrop-71231.firebasestorage.app',
    measurementId: 'G-19ZZWY4CEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw_9LPT5NrHBPkKSDfMxsqI4O85oUsKKo',
    appId: '1:962549560222:android:ea4d82cf837a3bc60e5c8f',
    messagingSenderId: '962549560222',
    projectId: 'acudrop-71231',
    storageBucket: 'acudrop-71231.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwJJC0I2ldyO3ZMq5hTY4Aep-voFLXFRY',
    appId: '1:962549560222:ios:9b2cf342584eb7850e5c8f',
    messagingSenderId: '962549560222',
    projectId: 'acudrop-71231',
    storageBucket: 'acudrop-71231.firebasestorage.app',
    iosBundleId: 'com.example.acudrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwJJC0I2ldyO3ZMq5hTY4Aep-voFLXFRY',
    appId: '1:962549560222:ios:9b2cf342584eb7850e5c8f',
    messagingSenderId: '962549560222',
    projectId: 'acudrop-71231',
    storageBucket: 'acudrop-71231.firebasestorage.app',
    iosBundleId: 'com.example.acudrop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaMGJwGBConRQKednkOT89IUnGDLlHxs4',
    appId: '1:962549560222:web:89d5d1dcfb19c0020e5c8f',
    messagingSenderId: '962549560222',
    projectId: 'acudrop-71231',
    authDomain: 'acudrop-71231.firebaseapp.com',
    storageBucket: 'acudrop-71231.firebasestorage.app',
    measurementId: 'G-BXD7JB28GR',
  );
}
